print(" _______")
print("|       |")
print("| O   O |")
print("|   __  |")
print("|_______|")
print("  |  |")
print(" __| |__")
print("| ____ |")
print("| |  | |")
print("| |__| |")
print("|______|")     
